#!/usr/bin/env python3
"""Analyze factory DFT fixtures and write a findings report."""

from __future__ import annotations

import sys
from pathlib import Path

# Allow `python tools/analyze_factory_files.py` from repo root.
_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import statistics
from collections import Counter
from dataclasses import dataclass, field

import click
from rich.console import Console
from rich.table import Table

from core.dft_parser import parse_dft, read_dft

DEFAULT_FIXTURES = Path(__file__).resolve().parent.parent / "tests" / "fixtures"
DEFAULT_REPORT = Path(__file__).resolve().parent.parent / "docs" / "findings.md"


@dataclass
class FactoryAnalysis:
    file_count: int = 0
    by_machine: Counter = field(default_factory=Counter)
    materials: Counter = field(default_factory=Counter)
    k_factors: Counter = field(default_factory=Counter)
    i_flags: Counter = field(default_factory=Counter)
    v_flags: Counter = field(default_factory=Counter)
    s_speed_token: Counter = field(default_factory=Counter)
    line_counts: list[int] = field(default_factory=list)
    extents: list[tuple[float, float]] = field(default_factory=list)
    anomalies: list[str] = field(default_factory=list)
    section_codes: dict[str, list[int]] = field(default_factory=dict)


def analyze_directory(fixtures_root: Path) -> FactoryAnalysis:
    analysis = FactoryAnalysis()
    for kind in ("punching", "laser"):
        folder = fixtures_root / kind
        for path in sorted(folder.glob("*.dft")):
            dft = parse_dft(path)
            analysis.file_count += 1
            analysis.by_machine[dft.machine_type] += 1
            analysis.materials[dft.material.name] += 1
            analysis.k_factors[dft.bend_params.k_factor] += 1
            i_flag = tuple(dft.machine_config.flags.get("I", []))
            v_flag = tuple(dft.machine_config.flags.get("V", []))
            analysis.i_flags[i_flag] += 1
            analysis.v_flags[v_flag] += 1
            s = dft.machine_config.flags.get("S", [])
            if len(s) > 11:
                analysis.s_speed_token[s[11]] += 1
            analysis.line_counts.append(dft.geometry.line_count)
            w, h = dft.machine_config.extent_width, dft.machine_config.extent_height
            if w is not None and h is not None:
                analysis.extents.append((w, h))

            expected_v = ("0", "2", "0", "1", "1") if kind == "punching" else ("1", "2", "0", "1", "1")
            if dft.machine_type != kind:
                analysis.anomalies.append(f"{path.name}: folder={kind} parsed={dft.machine_type}")
            if v_flag != expected_v:
                analysis.anomalies.append(
                    f"{path.name}: unexpected /V {v_flag} for {kind} (expected {expected_v})"
                )

            raw = read_dft(path)
            analysis.section_codes.setdefault(kind, raw.section_codes)

    return analysis


def render_findings_md(analysis: FactoryAnalysis) -> str:
    lc = analysis.line_counts
    extents = analysis.extents
    widths = [e[0] for e in extents]
    heights = [e[1] for e in extents]

    punch_codes = analysis.section_codes.get("punching", [])
    laser_codes = analysis.section_codes.get("laser", [])
    only_laser = sorted(set(laser_codes) - set(punch_codes))
    only_punch = sorted(set(punch_codes) - set(laser_codes))

    lines = [
        "# Factory DFT Findings",
        "",
        "Auto-generated by `tools/analyze_factory_files.py`.",
        "",
        "## Dataset",
        "",
        f"- Total DFT files parsed: **{analysis.file_count}**",
        f"- By machine type: {dict(analysis.by_machine)}",
        "",
        "## Materials & bend",
        "",
        f"- Materials: {dict(analysis.materials)}",
        f"- KFactor values: {dict(analysis.k_factors)}",
        "",
        "## Machine flags ([200])",
        "",
        f"- `/I` (machine): {dict(analysis.i_flags)}",
        f"- `/V`: {dict(analysis.v_flags)}",
        f"- `/S` token[11] (sheet speed-like): {dict(analysis.s_speed_token)}",
        "",
        "### Punch vs laser signature",
        "",
        "| Flag | Punching | Laser |",
        "|------|----------|-------|",
        "| `/I` | `0 0` | `0 1` |",
        "| `/V` | `0 2 0 1 1` | `1 2 0 1 1` |",
        "| `/S`[11] | ~110000 | ~80000 |",
        "",
        "## Geometry ([300] LINES)",
        "",
        f"- Line count min / max / mean: "
        f"**{min(lc)}** / **{max(lc)}** / **{statistics.mean(lc):.1f}**",
        f"- Unique sheet extents: **{len(set(extents))}**",
        f"- Extent width range: {min(widths):.3f} … {max(widths):.3f}",
        f"- Extent height range: {min(heights):.3f} … {max(heights):.3f}",
        "",
        "## Section markers",
        "",
        f"- Sections only in laser: `{only_laser}`",
        f"- Sections only in punching: `{only_punch}`",
        "",
        "## Anomalies",
        "",
    ]
    if analysis.anomalies:
        lines.extend(f"- {a}" for a in analysis.anomalies)
    else:
        lines.append("- None")
    lines.append("")
    return "\n".join(lines)


def print_console_summary(analysis: FactoryAnalysis, console: Console) -> None:
    table = Table(title="Factory DFT summary")
    table.add_column("Metric")
    table.add_column("Value")
    table.add_row("Files", str(analysis.file_count))
    table.add_row("Machines", str(dict(analysis.by_machine)))
    table.add_row("Materials", str(dict(analysis.materials)))
    table.add_row("Line counts", f"{min(analysis.line_counts)}–{max(analysis.line_counts)}")
    table.add_row("Anomalies", str(len(analysis.anomalies)))
    console.print(table)
    for a in analysis.anomalies:
        console.print(f"[yellow]![/yellow] {a}")


@click.command()
@click.option(
    "--fixtures",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    default=DEFAULT_FIXTURES,
    show_default=True,
)
@click.option(
    "--report",
    type=click.Path(path_type=Path),
    default=DEFAULT_REPORT,
    show_default=True,
)
def main(fixtures: Path, report: Path) -> None:
    """Scan punching/laser fixtures and write docs/findings.md."""
    console = Console()
    analysis = analyze_directory(fixtures)
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(render_findings_md(analysis), encoding="utf-8")
    print_console_summary(analysis, console)
    console.print(f"Wrote [green]{report}[/green]")


if __name__ == "__main__":
    main()
