#!/usr/bin/env python3
"""Batch-validate DXF→DFT generation against factory reference DFTs."""

from __future__ import annotations

import json
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import click
from rich.console import Console
from rich.table import Table

from core.dxf_to_dft import convert_dxf_to_dft_file
from core.validator import compare_dft_files

DEFAULT_DXF = _ROOT / "tests" / "fixtures" / "dxf"
DEFAULT_PUNCH = _ROOT / "tests" / "fixtures" / "punching"
DEFAULT_LASER = _ROOT / "tests" / "fixtures" / "laser"
DEFAULT_OUT = _ROOT / "output" / "validation"


@dataclass
class PartResult:
    part: str
    machine_type: str
    ok: bool
    coverage: float
    matched: int
    ref_lines: int
    gen_lines: int
    parameter_diffs: list[str] = field(default_factory=list)
    error: str = ""


def find_reference(folder: Path, stem: str) -> Path | None:
    matches = list(folder.glob(f"* {stem}.dft")) + list(folder.glob(f"{stem}.dft"))
    return matches[0] if matches else None


def validate_one(
    dxf: Path,
    *,
    machine_type: str,
    reference_dir: Path,
    output_dir: Path,
    tolerance: float,
    min_coverage: float,
) -> PartResult:
    stem = dxf.stem
    ref = find_reference(reference_dir, stem)
    if ref is None:
        return PartResult(
            part=stem,
            machine_type=machine_type,
            ok=False,
            coverage=0.0,
            matched=0,
            ref_lines=0,
            gen_lines=0,
            error=f"no reference DFT for {stem}",
        )
    out = output_dir / machine_type / f"{stem}.dft"
    try:
        convert_dxf_to_dft_file(dxf, out, machine_type=machine_type)  # type: ignore[arg-type]
        cmp = compare_dft_files(
            ref,
            out,
            tolerance=tolerance,
            check_parameters=True,
            unordered=True,
            min_coverage=min_coverage,
        )
        return PartResult(
            part=stem,
            machine_type=machine_type,
            ok=cmp.ok,
            coverage=cmp.reference_coverage,
            matched=cmp.matched_lines,
            ref_lines=cmp.reference_line_count,
            gen_lines=cmp.other_line_count,
            parameter_diffs=list(cmp.parameter_diffs),
        )
    except Exception as exc:  # noqa: BLE001 — batch must keep going
        return PartResult(
            part=stem,
            machine_type=machine_type,
            ok=False,
            coverage=0.0,
            matched=0,
            ref_lines=0,
            gen_lines=0,
            error=str(exc),
        )


def render_report_md(results: list[PartResult]) -> str:
    punch = [r for r in results if r.machine_type == "punching"]
    laser = [r for r in results if r.machine_type == "laser"]

    def stats(rows: list[PartResult]) -> str:
        if not rows:
            return "n/a"
        ok = sum(1 for r in rows if r.ok)
        cov = sum(r.coverage for r in rows) / len(rows)
        return f"{ok}/{len(rows)} ok ({100 * ok / len(rows):.1f}%), mean coverage {100 * cov:.1f}%"

    lines = [
        "# Batch Validation Report",
        "",
        "Generated by `tools/batch_process.py`.",
        "",
        "## Summary",
        "",
        f"- Punching: **{stats(punch)}**",
        f"- Laser: **{stats(laser)}**",
        "",
        "## Per-part results",
        "",
        "| Part | Type | OK | Coverage | Matched | Ref | Gen | Notes |",
        "|------|------|----|----------|---------|-----|-----|-------|",
    ]
    for r in results:
        notes = r.error or ("; ".join(r.parameter_diffs) if r.parameter_diffs else "")
        lines.append(
            f"| {r.part} | {r.machine_type} | {'yes' if r.ok else 'no'} | "
            f"{100 * r.coverage:.1f}% | {r.matched} | {r.ref_lines} | {r.gen_lines} | {notes} |"
        )
    lines.append("")
    return "\n".join(lines)


@click.command()
@click.option("--dxf-dir", type=click.Path(exists=True, file_okay=False, path_type=Path), default=DEFAULT_DXF)
@click.option("--reference-punch-dir", type=click.Path(exists=True, file_okay=False, path_type=Path), default=DEFAULT_PUNCH)
@click.option("--reference-laser-dir", type=click.Path(exists=True, file_okay=False, path_type=Path), default=DEFAULT_LASER)
@click.option("--output-dir", type=click.Path(path_type=Path), default=DEFAULT_OUT)
@click.option("--tolerance", default=0.05, show_default=True)
@click.option(
    "--min-coverage",
    default=0.90,
    show_default=True,
    help="Fraction of factory reference lines that must appear in generated DFT.",
)
@click.option("--limit", default=0, help="Process only first N DXFs (0 = all).")
def main(
    dxf_dir: Path,
    reference_punch_dir: Path,
    reference_laser_dir: Path,
    output_dir: Path,
    tolerance: float,
    min_coverage: float,
    limit: int,
) -> None:
    """Generate punching+laser DFTs from each DXF and compare to factory refs."""
    console = Console()
    dxfs = sorted(dxf_dir.glob("*.dxf"))
    if limit > 0:
        dxfs = dxfs[:limit]
    output_dir.mkdir(parents=True, exist_ok=True)

    results: list[PartResult] = []
    for dxf in dxfs:
        for machine, ref_dir in (("punching", reference_punch_dir), ("laser", reference_laser_dir)):
            r = validate_one(
                dxf,
                machine_type=machine,
                reference_dir=ref_dir,
                output_dir=output_dir,
                tolerance=tolerance,
                min_coverage=min_coverage,
            )
            results.append(r)
            status = "[green]OK[/green]" if r.ok else "[red]FAIL[/red]"
            console.print(
                f"{status} {r.part}/{machine} coverage={100 * r.coverage:.1f}% "
                f"({r.matched}/{r.ref_lines})"
                + (f" err={r.error}" if r.error else "")
            )

    report = output_dir / "report.md"
    report.write_text(render_report_md(results), encoding="utf-8")
    (output_dir / "report.json").write_text(
        json.dumps([asdict(r) for r in results], indent=2),
        encoding="utf-8",
    )

    ok = sum(1 for r in results if r.ok)
    table = Table(title="Batch validation")
    table.add_column("Metric")
    table.add_column("Value")
    table.add_row("Parts × types", str(len(results)))
    table.add_row("Passed", f"{ok}/{len(results)}")
    table.add_row("Report", str(report))
    console.print(table)
    sys.exit(0 if ok == len(results) else 1)


if __name__ == "__main__":
    main()
